#!/usr/bin/env bash
echo "Choose a sound card: "
card=$(pactl list short cards | dmenu)
card=$(echo "$card" | awk '{print $1}')
echo "$card"
echo "Now, choose your desired configuration: "
config=$(pactl list cards \
    | grep -A 100 "#$card" \
    | sed -e 's/\t/#/g' \
    | tr -d '\n' \
    | grep -o "Profiles.*Active" \
    | tr -d '\t' \
    | sed -e 's/#Active//' -e 's/Profiles://' -e 's/##/\n/g' \
    | cut -d ' ' -f 1 \
    | sed 's/:$//g' | dmenu)
echo "set card $card to $config? (y/n)"
read cmd
if [[ "$cmd" == "y" ]]
then
    pactl set-card-profile $card $config
    pactl list short sinks
else
    echo "doing nothing."
fi
